= Hot Methods

En este laboratorio veremos como encontrar los métodos mas ejecutados.

*_Para ejecutar jcmd en este laboratorio vamos a necesitar Oracle JDK 8 o Open JDK 11_*

*Nota*: Generalmente estos "Hot spots" son un buen lugar para empezar a optimizar.

1) Abrir una terminal y ejecutar

[source,bash]
----
./run.sh -l hot_methods
----

2) Ejecutar jvmtop

[source,bash]
----
./tools/jvmtop.sh -p <PID>
----

3) Ahora vamos a iniciar JFR desde jcmd

[source,bash]
----
jcmd <PID> JFR.start settings=profile
----

4) Hacemos el dump del recording

[source,bash]
----
jcmd <PID> JFR.dump name=<RECORDING_ID> filename=<RECORDING_FILE_PATH>.jfr
----

5) Detenemos la grabación

[source,bash]
----
jcmd <PID> JFR.stop name=<RECORDING_ID>
----

6) Abrir el jfr en Java Mission Control

Podemos utilizar el tab `Java Application` y ver el stack de nuestros threads o `Method Profiling` que nos brinda mas información.

== Opcional

1) Podemos iniciar JFR para grabar durante un tiempo determinado

[source,bash]
----
jcmd <PID> JFR.start filename=hot_methods_jcmd.jfr settings=profile delay=5s duration=30s
----

2) Podemos ver el estado de JFR

[source,bash]
----
jcmd <PID> JFR.check
----

3) Otra alternativa es VisualVM

* Abrir el proceso Java en VisualVM
* Ir al tab Sampler
* Utilizar el modo CPU
* Hacer click en el botón "Hot spots"

== Preguntas

1) ¿Qué clase/método está consumiendo más recursos?

+++ <details><summary> +++
See `answer`:
+++ </summary><div> +++
----
Luego de ver los hot methods y el stack trace vemos algunas clases de la JVM y ahi vemos que clase de nuestro codigo esta siendo invocado. En este caso NumberGenerator#countIntersection
----
+++ </div></details> +++

2) ¿Qué podríamos mejorar nuestra aplicación?

+++ <details><summary> +++
See `answer`:
+++ </summary><div> +++
----
Muchas optimizaciones o mejoran van de la mano de la logica de la aplicacion, en este caso especifico podemos utilizar un Set en lugar de LinkedList.
----
+++ </div></details> +++

