= Labs

Estos laboratorios nos ayudaran a entender de forma practica las herramientas que tenemos para analizar la JVM, asi como profundizar en algunos conceptos.

* link:JDKTools.adoc[Lab 1 - JDK Tools]
* link:Deadlock.adoc[Lab 2 - Deadlock]
* link:HiddenDeadlock.adoc[Lab 3 - Hidden Deadlock]
* link:CircularDeadlock.adoc[Lab 4 - Circular Deadlock]
* link:BusyThread.adoc[Lab 5 - Busy Thread]
* link:ZombieProcess.adoc[Lab 6 - Zombie Process]
* link:HotMethods.adoc[Lab 7 - Hot Methods]
* link:MemoryVisibility.adoc[Lab 8 - Memory Visibility]
* link:Latency.adoc[Lab 9 - Latency]
* link:MemoryAllocation.adoc[Lab 10 - Memory Allocation]
* link:LoadClasses.adoc[Lab 11 - Load Classes]
* link:MultipleClassloaders.adoc[Lab 12 - Multiple Class loaders]
* link:Exceptions.adoc[Lab 13 - Exceptions]
* link:GC.adoc[Lab 14 - GC]
* link:FileLeak.adoc[Lab 15 - File Leak]
* link:JITCompiler.adoc[Lab 16 - JIT Compiler]
* link:NativeMemory.adoc[Lab 17 - Native Memory]
* link:Safepoints.adoc[Lab 18 - Safepoints]

*Nota*: Debemos ejecutar `./mvnw clean package`, antes de utilizar los laboratorios.

== Requerimientos

Para ejecutar los laboratorios debemos instalar las tools que se mencionan link:../tools/README.adoc#AdditionalTools[aquí].

Estas pueden ser instaladas con el script `provision_mac.sh`.

*Nota*: El script solo es valido en _macOS_.

== Docker

1) Crear la docker image

[source,bash]
----
docker build -t jvm-troubleshooting-workshop:labs-alpine .
----

2) Ejecutar el container

[source,bash]
----
docker run -it -v $(pwd):/labs jvm-troubleshooting-workshop:labs-alpine /bin/sh
----

3) Obtener el Container ID

[source,bash]
----
docker ps --filter ancestor=jvm-troubleshooting-workshop:labs-alpine
----

4) Abrir una nueva terminal para interactuar con ese container

[source,bash]
----
docker exec -it <CONTAINER ID> /bin/sh

o

docker exec -it $(docker ps -q --filter ancestor=jvm-troubleshooting-workshop:labs-alpine) /bin/sh
----